# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datarate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr', models.FloatField()),
            ],
            options={
                'db_table': 'datarate',
            },
        ),
    ]
